# Generated by Django 3.1.8 on 2021-05-20 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import videos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSnippet',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=500, validators=[videos.validators.validate_youtube_url])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='VideoAuthorsOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authorsnippet')),
                ('video', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_authors', to='videos.videosnippet')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
