# Generated by Django 3.1.8 on 2021-06-03 19:50

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosnippet',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, max_length=255, populate_from='title', primary_key=True, serialize=False, unique=True),
        ),
    ]
