# Generated by Django 3.1.12 on 2021-06-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20210614_1318'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoauthorsorderable',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authorpage'),
        ),
    ]
