# Generated by Django 3.1.8 on 2021-05-20 08:05

from django.db import migrations, models
import videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosnippet',
            name='slug',
            field=models.SlugField(default='', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='videosnippet',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='videosnippet',
            name='url',
            field=models.URLField(default='', max_length=500, validators=[videos.validators.validate_youtube_url]),
        ),
    ]
