# Generated by Django 3.2.5 on 2021-11-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videospage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosnippet',
            name='title',
            field=models.CharField(default='Hello', max_length=255),
        ),
    ]
