# Generated by Django 3.2.5 on 2022-02-23 18:46

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videosnippet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoauthorsorderable',
            name='video',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videosnippet'),
        ),
    ]
