# Generated by Django 3.2.5 on 2022-02-23 18:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_videoauthorsorderable_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosnippet',
            name='authors',
            field=models.ManyToManyField(to='videos.VideoAuthorsOrderable'),
        ),
        migrations.AlterField(
            model_name='videoauthorsorderable',
            name='video',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_authors', to='videos.videosnippet'),
        ),
    ]
