# Generated by Django 3.2.5 on 2022-02-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20220223_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosnippet',
            name='authors',
        ),
    ]
