# Generated by Django 3.2.5 on 2022-02-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_videosnippet_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosnippet',
            name='v_authors',
            field=models.ManyToManyField(related_name='video_authors', to='videos.VideoAuthorsOrderable'),
        ),
    ]
