# Generated by Django 3.1.8 on 2021-06-03 19:50

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsnippet',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='full_name', primary_key=True, serialize=False, unique=True),
        ),
    ]
