# Generated by Django 3.1.12 on 2021-07-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_authorpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='legacy_facebook_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='legacy_twitter_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
