# Generated by Django 3.1.12 on 2021-06-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210614_1318'),
        ('videos', '0002_auto_20210614_1318'),
        ('authors', '0002_auto_20210614_1318'),
        ('article', '0004_auto_20210614_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorSnippet',
        ),
        migrations.AddField(
            model_name='authorpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.ubysseyimage'),
        ),
    ]
