# Generated by Django 3.1.12 on 2021-06-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_authorpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
