# Generated by Django 3.1.12 on 2021-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20210709_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='legacy_slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
