# Generated by Django 3.1.8 on 2021-06-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='current_section',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
