# Generated by Django 3.1.12 on 2021-07-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysnippet',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='categorysnippet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
