# Generated by Django 3.1.12 on 2021-07-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20210705_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysnippet',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
