# Generated by Django 3.1.8 on 2021-06-03 23:55

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_auto_20210526_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsectionsorderable',
            name='subsection_name',
        ),
        migrations.AddField(
            model_name='subsectionsnippet',
            name='section_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='section.sectionpage', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='subsectionsnippet',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='subsectionsorderable',
            name='section_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection_menu', to='section.sectionpage'),
        ),
    ]
