# Generated by Django 3.1.8 on 2021-06-04 02:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_auto_20210603_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from='name')),
                ('section_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection_menu', to='section.sectionpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='subsectionsorderable',
            name='section_page',
        ),
        migrations.RemoveField(
            model_name='subsectionsorderable',
            name='subsection_snippet',
        ),
        migrations.DeleteModel(
            name='SubsectionSnippet',
        ),
        migrations.DeleteModel(
            name='SubsectionsOrderable',
        ),
    ]
