# Generated by Django 3.1.8 on 2021-06-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_auto_20210603_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsections',
            new_name='Subsection',
        ),
    ]
