# Generated by Django 3.1.8 on 2021-06-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0006_auto_20210603_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefilteredSubsection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('section.subsection',),
        ),
    ]
