# Generated by Django 3.2.5 on 2021-08-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('div_id', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.CharField(choices=[('box', 'Box'), ('skyscraper', 'SkyScraper'), ('banner', 'Banner'), ('leaderboard', 'Leaderboard'), ('mobile-leaderboard', 'Mobile Leaderboard')], default='box', max_length=255)),
                ('dfp', models.CharField(blank=True, default='', max_length=255)),
                ('template', models.CharField(choices=[('ads/advertisement.html', 'ads/advertisement.html')], default='ads/advertisement.html', max_length=255)),
            ],
        ),
    ]
