# Generated by Django 3.2.5 on 2021-08-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_adslot_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='div_class',
            field=models.CharField(choices=[('', 'Default'), ('homepage', 'Homepage'), ('mobile-frontpage-box', 'Mobile Frontpage Box')], default='box', max_length=255),
        ),
    ]
