# Generated by Django 3.2.5 on 2021-09-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20210826_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsettings',
            options={'verbose_name': 'Ad Settings', 'verbose_name_plural': "Instances of 'Ad Settings'"},
        ),
        migrations.AddField(
            model_name='adsettings',
            name='article_right_column_boxA_ad_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ads.adslot'),
        ),
        migrations.AddField(
            model_name='adsettings',
            name='article_right_column_boxB_ad_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ads.adslot'),
        ),
        migrations.AddField(
            model_name='adsettings',
            name='article_right_column_skyscraper_ad_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ads.adslot'),
        ),
    ]
