# Generated by Django 3.2.5 on 2021-09-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20210904_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsettings',
            options={'verbose_name': 'Side-Wide Ad Slots', 'verbose_name_plural': "Instances of \\Side-Wide Ad Slots'"},
        ),
        migrations.AlterField(
            model_name='adslot',
            name='div_class',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('homepage', 'Homepage'), ('mobile-frontpage-box', 'Mobile Frontpage Box')], default='box', max_length=255),
        ),
    ]
