# Generated by Django 3.2.11 on 2022-07-04 23:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20220610_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adtagsettings',
            options={'verbose_name': 'Ad Settings', 'verbose_name_plural': "Instances of 'Ad Settings'"},
        ),
        migrations.RemoveField(
            model_name='adheadorderable',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='adplacementorderable',
            name='settings',
        ),
        migrations.CreateModel(
            name='ArticleAdHeadOrderable',
            fields=[
                ('adplacementorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.adplacementorderable')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_head_tags', to='ads.adtagsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('ads.adplacementorderable',),
        ),
        migrations.CreateModel(
            name='ArticleHeaderPlacementOrderable',
            fields=[
                ('adplacementorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.adplacementorderable')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_header_placements', to='ads.adtagsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('ads.adplacementorderable',),
        ),
        migrations.CreateModel(
            name='ArticleSidebarPlacementOrderable',
            fields=[
                ('adplacementorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.adplacementorderable')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sidebar_placements', to='ads.adtagsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('ads.adplacementorderable',),
        ),
        migrations.CreateModel(
            name='HomeAdHeadOrderable',
            fields=[
                ('adplacementorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.adplacementorderable')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_head_tags', to='ads.adtagsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('ads.adplacementorderable',),
        ),
        migrations.CreateModel(
            name='HomeHeaderPlacementOrderable',
            fields=[
                ('adplacementorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.adplacementorderable')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_header_placements', to='ads.adtagsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('ads.adplacementorderable',),
        ),
        migrations.CreateModel(
            name='HomeSidebarPlacementOrderable',
            fields=[
                ('adplacementorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.adplacementorderable')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_sidebar_placements', to='ads.adtagsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('ads.adplacementorderable',),
        ),
        migrations.CreateModel(
            name='SectionAdHeadOrderable',
            fields=[
                ('adplacementorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.adplacementorderable')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_head_tags', to='ads.adtagsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('ads.adplacementorderable',),
        ),
        migrations.CreateModel(
            name='SectionHeaderPlacementOrderable',
            fields=[
                ('adplacementorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.adplacementorderable')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_header_placements', to='ads.adtagsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('ads.adplacementorderable',),
        ),
        migrations.DeleteModel(
            name='AdSettings',
        ),
    ]
