# Generated by Django 3.1.8 on 2021-05-21 22:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        ('article', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='featured_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.videosnippet'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='article.sectionsnippet'),
        ),
        migrations.AddField(
            model_name='articleauthorsorderable',
            name='article_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='article.articlepage'),
        ),
        migrations.AddField(
            model_name='articleauthorsorderable',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authorsnippet'),
        ),
    ]
