# Generated by Django 3.1.8 on 2021-06-04 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='featured_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.videosnippet'),
        ),
    ]
