# Generated by Django 3.1.12 on 2021-07-09 10:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('section', '0001_initial'),
        ('images', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('dispatch', '0108_auto_20210511_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.categorysnippet'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='dispatch_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.article'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='article.ArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='articlefeaturedmediaorderable',
            name='article_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_media', to='article.articlepage'),
        ),
        migrations.AddField(
            model_name='articlefeaturedmediaorderable',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.ubysseyimage'),
        ),
    ]
