# Generated by Django 3.1.12 on 2021-06-24 20:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('videos', '0001_initial'),
        ('authors', '0002_authorpage_image'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('article', '0002_auto_20210624_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='featured_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.videosnippet'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='article.ArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='articlefeaturedmediaorderable',
            name='article_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_media', to='article.articlepage'),
        ),
        migrations.AddField(
            model_name='articlefeaturedmediaorderable',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.ubysseyimage'),
        ),
        migrations.AddField(
            model_name='articlefeaturedmediaorderable',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.videosnippet'),
        ),
        migrations.AddField(
            model_name='articleauthorsorderable',
            name='article_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='article.articlepage'),
        ),
        migrations.AddField(
            model_name='articleauthorsorderable',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='authors.authorpage'),
        ),
        migrations.AddIndex(
            model_name='articlepage',
            index=models.Index(fields=['category'], name='article_art_categor_64ad02_idx'),
        ),
    ]
