# Generated by Django 3.1.6 on 2021-04-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0102_auto_20200921_2009'),
        ('article', '0002_auto_20210408_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='dispatch_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.article'),
        ),
    ]
