# Generated by Django 3.1.8 on 2021-06-04 04:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('section', '0001_initial'),
        ('article', '0002_articlepage_featured_video'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.subsection'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='article.ArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='articlefeaturedimagesorderable',
            name='article_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_images', to='article.articlepage'),
        ),
        migrations.AddField(
            model_name='articlefeaturedimagesorderable',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.ubysseyimage'),
        ),
        migrations.AddField(
            model_name='articleauthorsorderable',
            name='article_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='article.articlepage'),
        ),
        migrations.AddField(
            model_name='articleauthorsorderable',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authorsnippet'),
        ),
        migrations.AddIndex(
            model_name='articlepage',
            index=models.Index(fields=['subsection'], name='article_art_subsect_2dd71e_idx'),
        ),
    ]
