# Generated by Django 3.1.8 on 2021-06-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210603_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='current_section',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
