# Generated by Django 3.1.8 on 2021-05-21 23:22

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210521_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='excerpt',
            new_name='lede',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='seo_keyword',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(help_text='Write your article contents here. See documentation: https://docs.wagtail.io/en/latest/editor_manual/new_pages/creating_body_content.html#rich-text-fields', label='Rich Text Block')), ('plaintext', wagtail.core.blocks.TextBlock(help_text='Warning: Rich Text Blocks preferred! Plain text primarily exists for importing old Dispatch text.', label='Plain Text Block')), ('dropcap', wagtail.core.blocks.TextBlock(help_text='Create a block where special dropcap styling with be applied to the first letter and the first letter only.\n\nThe contents of this block will be enclosed in a <p class="drop-cap">...</p> element, allowing its targetting for styling.\n\nNo RichText allowed.', label='Dropcap Block', template='article/stream_blocks/dropcap.html')), ('pagebreak', wagtail.core.blocks.static_block.StaticBlock(label='Pagebreak - USE RICHTEXT INSTEAD', template='article/stream_blocks/pagebreak.html')), ('video', wagtail.core.blocks.StructBlock([('video_embed', wagtail.embeds.blocks.EmbedBlock(blank=False, null=False)), ('title', wagtail.core.blocks.CharBlock()), ('caption', wagtail.core.blocks.CharBlock()), ('credit', wagtail.core.blocks.CharBlock())], help_text='Use this for videos that will only be associated with this current article, rather than entered into our video library', label='One Off Video Block', template='article/stream_blocks/video.html')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image'))], blank=True, null=True),
        ),
    ]
