# Generated by Django 3.1.12 on 2021-07-09 10:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        ('authors', '0002_authorpage_image'),
        ('article', '0002_auto_20210709_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefeaturedmediaorderable',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.videosnippet'),
        ),
        migrations.AddField(
            model_name='articleauthorsorderable',
            name='article_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='article.articlepage'),
        ),
        migrations.AddField(
            model_name='articleauthorsorderable',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='authors.authorpage'),
        ),
        migrations.AddIndex(
            model_name='articlepage',
            index=models.Index(fields=['category'], name='article_art_categor_64ad02_idx'),
        ),
    ]
