# Generated by Django 3.1.12 on 2021-07-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210709_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='legacy_template',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
