# Generated by Django 3.1.8 on 2021-05-03 20:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepage_dispatch_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='excerpt',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
