# Generated by Django 3.1.8 on 2021-05-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210521_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='seo_description',
            field=models.TextField(blank=True, default='', verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='seo_keyword',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SEO Keyword'),
        ),
    ]
