# Generated by Django 3.1.12 on 2021-06-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210615_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='explicit_published_at',
            field=models.DateTimeField(blank=True, help_text='Optional. Publication date which is explicitly shown to the reader. Articles are seperately date/timestamped for database use; if this field is blank front page etc. will display the database publication date.', null=True, verbose_name='Published At (Override)'),
        ),
    ]
