# Generated by Django 3.1.8 on 2021-05-27 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210527_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='created_at_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='legacy_published_at_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='legacy_revised_at_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='revision_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='is_explicit',
            field=models.BooleanField(default=False, help_text='Check if this article contains advertiser-unfriendly content. Disables ads for this specific article.', verbose_name='Is Explicit?'),
        ),
    ]
