# Generated by Django 3.1.8 on 2021-05-21 23:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210521_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='breaking_timeout',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 23, 38, 40, 472113, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='is_breaking',
            field=models.BooleanField(default=False, verbose_name='Breaking News?'),
        ),
    ]
