# Generated by Django 3.1.12 on 2021-06-18 00:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('videos', '0002_auto_20210617_1707'),
        ('article', '0004_auto_20210615_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFeaturedMediaOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('credit', models.TextField(blank=True, default='')),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_media', to='article.articlepage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.ubysseyimage')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.videosnippet')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ArticleFeaturedImagesOrderable',
        ),
    ]
