# Generated by Django 3.1.12 on 2021-07-20 23:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210719_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSeriesSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Series of Articles',
                'verbose_name_plural': 'Series of Articles',
            },
        ),
        migrations.CreateModel(
            name='SeriesOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='article.articlepage')),
                ('series', modelcluster.fields.ParentalKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.articleseriessnippet')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
