# Generated by Django 3.1.12 on 2021-06-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210617_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='legacy_published_at_time',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='legacy_revised_at_time',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='revision_id',
        ),
    ]
