# Generated by Django 3.1.8 on 2021-05-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0108_auto_20210511_1359'),
        ('article', '0005_auto_20210518_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchCounterpartSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.article')),
            ],
        ),
    ]
