# Generated by Django 3.1.8 on 2021-05-27 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210527_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='publication_date',
            field=models.DateField(default=datetime.date(1918, 10, 17), help_text='To be explicitly shown to the reader. Defaults to today. Articles are seperately date/timestamped for database use, so editors can explicitly override the displayed date.'),
        ),
    ]
