# Generated by Django 3.1.12 on 2021-06-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210618_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='legacy_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='legacy_template_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
