# Generated by Django 3.1.8 on 2021-05-26 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210525_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='breaking_timeout',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 20, 31, 53, 546049, tzinfo=utc)),
        ),
    ]
