# Generated by Django 3.1.8 on 2021-05-26 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210526_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='breaking_timeout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
