# Generated by Django 3.1.8 on 2021-05-20 00:16

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_authorsnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthorsOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author_role', models.CharField(blank=True, max_length=50, null=True)),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='article.articlepage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.authorsnippet')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
