# Generated by Django 3.1.8 on 2021-05-27 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210527_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='legacy_published_at_time',
            field=models.DateTimeField(default=datetime.datetime(1918, 10, 17, 0, 0), null=True),
        ),
    ]
