# Generated by Django 3.1.12 on 2021-06-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210628_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='legacy_revision_number',
            field=models.IntegerField(default=0),
        ),
    ]
