# Generated by Django 3.2.5 on 2021-08-10 22:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('dbtemplates', '0001_initial'),
        ('article', '0008_articlepage_article_art_current_4f959d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='db_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dbtemplates.template'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='fw_about_this_article',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='fw_above_cut_lede',
            field=models.TextField(blank=True, default='', help_text='Articles that use a special header/banner often contain a second lede/abstract summary ', verbose_name='Above Cut Lede (Optional)'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='fw_alternate_title',
            field=models.CharField(blank=True, default='', help_text='When there is a "special feature" or full-width style article, sometimes we would like to override the title as it render in the template', max_length=255, verbose_name='Alternate Title (Optional)'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='fw_optional_subtitle',
            field=models.CharField(blank=True, default='', help_text='When there is a "special feature" or full-width style article, sometime we want to add a subtitle alongside the title', max_length=255, verbose_name='Subtitle (Optional)'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='header_layout',
            field=models.CharField(blank=True, default='', help_text='Legacy from Dispatch\'s "Templates" feature', max_length=50),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='image_size',
            field=models.CharField(default='default', help_text='Legacy from Dispatch\'s "Templates" feature', max_length=50),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='layout',
            field=models.CharField(default='default', help_text='These correspond to very frequently used templates. More "bespoke", one-off templates should be added to the library of DB Templates', max_length=100, verbose_name='Article Layout'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='use_default_template',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MagazineArticleBylineOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('byline', models.TextField(blank=True, default='')),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_bylines', to='article.articlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectedArticleOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article_description', models.TextField(blank=True, default='')),
                ('connected_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='article.articlepage')),
                ('parent_article', modelcluster.fields.ParentalKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='connected_articles', to='article.articlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleStyleOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='article.articlepage')),
                ('css', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleScriptOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='article.articlepage')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
