# Generated by Django 3.1.8 on 2021-05-20 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_articleauthorsorderable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSnippet',
            fields=[
                ('slug', models.SlugField(default='news', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='News', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.AlterModelOptions(
            name='articlepage',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='articlepage',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='article.sectionsnippet'),
        ),
    ]
