# Generated by Django 3.1.8 on 2021-05-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20210519_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_used', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.AlterField(
            model_name='articleauthorsorderable',
            name='author_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='authorsnippet',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['slug'], name='article_top_slug_8896c6_idx'),
        ),
    ]
