# Generated by Django 3.1.8 on 2021-06-01 00:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20210528_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='featured_image',
        ),
        migrations.CreateModel(
            name='ArticleFeaturedImagesOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('credit', models.TextField(blank=True, default='')),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_images', to='article.articlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
