# Generated by Django 3.2.5 on 2021-08-04 21:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('article', '0009_articlescriptorderable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.articlepage')),
                ('alternate_title', models.CharField(blank=True, default='', max_length=255)),
                ('optional_subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('above_cut_lede', models.TextField(blank=True, default='')),
                ('about_this_article', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
        migrations.CreateModel(
            name='FWTypeArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.articlepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
        migrations.CreateModel(
            name='GuideArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.articlepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
        migrations.CreateModel(
            name='MagazineArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.articlepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
        migrations.CreateModel(
            name='ArticleStyleOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='article.articlepage')),
                ('css', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
