# Generated by Django 3.2.5 on 2021-08-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_articlestyleorderable_featurearticlepage_fwtypearticlepage_guidearticlepage_magazinearticlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='use_default_template',
            field=models.BooleanField(default=True),
        ),
    ]
