# Generated by Django 3.1.8 on 2021-05-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20210519_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorsnippet',
            name='image',
        ),
    ]
