# Generated by Django 3.2.5 on 2021-08-18 23:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20210811_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('data', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='image_size',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='show_timeline',
            field=models.BooleanField(default=False, help_text='Layout MUST be full-width (or else customized) to display a timeline'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='timeline_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articleauthorsorderable',
            name='author_role',
            field=models.CharField(blank=True, default='author', max_length=50),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='header_layout',
            field=models.CharField(default='right-image', help_text='Based on from Dispatch\'s obselete "Templates" feature', max_length=50),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='timeline',
            field=models.ForeignKey(blank=True, help_text='Create a timeline in the Snippets menu and set it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_articles', to='article.timelinesnippet'),
        ),
    ]
