# Generated by Django 3.1.8 on 2021-06-01 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20210531_1743'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefeaturedimagesorderable',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.ubysseyimage'),
        ),
    ]
