# Generated by Django 3.1.8 on 2021-06-01 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_articlefeaturedimagesorderable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(1918, 10, 17, 0, 0), help_text='To be explicitly shown to the reader. Articles are seperately date/timestamped for database use, so editors can explicitly override the displayed date.'),
        ),
    ]
