# Generated by Django 3.1.8 on 2021-05-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_remove_authorsnippet_image'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauthorsorderable',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authorsnippet'),
        ),
        migrations.DeleteModel(
            name='AuthorSnippet',
        ),
    ]
