# Generated by Django 3.2.5 on 2021-11-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20210818_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='explicit_published_at',
            field=models.DateTimeField(blank=True, help_text='Techically optional (computer will fill it in for you if you do not). Publication date which is explicitly shown to the reader. Articles are seperately date/timestamped for database use; if this field is left blank, it will by default be set to the "first published date" on publication.', null=True, verbose_name='Publication Date/Time'),
        ),
    ]
