# Generated by Django 3.2.5 on 2021-08-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0001_initial'),
        ('article', '0011_articlepage_use_default_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='db_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dbtemplates.template'),
        ),
    ]
