# Generated by Django 3.2.5 on 2022-01-20 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_articlepage_explicit_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialArticleLikePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.articlepage')),
            ],
            options={
                'verbose_name': 'Special Article-Like Page (for About Page, Contact, etc.)',
                'verbose_name_plural': 'Articles',
            },
            bases=('article.articlepage',),
        ),
    ]
