# Generated by Django 3.1.8 on 2021-06-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_prefilteredsubsection'),
        ('article', '0012_auto_20210531_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='section.prefilteredsubsection'),
        ),
    ]
