# Generated by Django 3.2.5 on 2021-11-22 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import images.models
import modelcluster.contrib.taggit
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0001_initial'),
        ('dispatch', '0108_auto_20210511_1359'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('section', '0001_initial'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('article', '0012_alter_articlepage_explicit_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('current_section', models.CharField(blank=True, default='', max_length=255)),
                ('content', wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(help_text='Write your article contents here. See documentation: https://docs.wagtail.io/en/latest/editor_manual/new_pages/creating_body_content.html#rich-text-fields', label='Rich Text Block')), ('plaintext', wagtail.core.blocks.TextBlock(help_text='Warning: Rich Text Blocks preferred! Plain text primarily exists for importing old Dispatch text.', label='Plain Text Block')), ('dropcap', wagtail.core.blocks.TextBlock(help_text='DO NOT USE - Legacy block. Create a block where special dropcap styling with be applied to the first letter and the first letter only.\n\nThe contents of this block will be enclosed in a <p class="drop-cap">...</p> element, allowing its targetting for styling.\n\nNo RichText allowed.', label='Dropcap Block', template='article/stream_blocks/dropcap.html')), ('video', wagtail.core.blocks.StructBlock([('video_embed', wagtail.embeds.blocks.EmbedBlock(blank=False, null=False)), ('title', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('caption', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('credit', wagtail.core.blocks.CharBlock(max_length=255, required=False))], help_text='Use this to credit or caption videos that will only be associated with this current article, rather than entered into our video library. You can also embed videos in a Rich Text Block.', label='Credited/Captioned One-Off Video')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('style', wagtail.core.blocks.ChoiceBlock(choices=[('default', 'Default'), ('left', 'Left'), ('right', 'Right')])), ('width', wagtail.core.blocks.ChoiceBlock(choices=[('full', 'Full'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')])), ('caption', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('credit', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('raw_html', wagtail.core.blocks.RawHTMLBlock(help_text="WARNING: DO NOT use this unless you really know what you're doing!", label='Raw HTML Block')), ('quote', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.CharBlock(required=False)), ('source', wagtail.core.blocks.CharBlock(required=False))], label='Pull Quote', template='article/stream_blocks/quote.html')), ('gallery', wagtail.snippets.blocks.SnippetChooserBlock(target_model=images.models.GallerySnippet, template='article/stream_blocks/gallery.html'))], blank=True, null=True)),
                ('explicit_published_at', models.DateTimeField(blank=True, help_text='Techically optional (computer will fill it in for you if you do not). Publication date which is explicitly shown to the reader. Articles are seperately date/timestamped for database use; if this field is left blank, it will by default be set to the "first published date" on publication.', null=True, verbose_name='Publication Date/Time')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('show_last_modified', models.BooleanField(default=False, help_text='Check this to alert readers the article has been revised since its publication.')),
                ('lede', models.TextField(blank=True, default='')),
                ('is_breaking', models.BooleanField(default=False, verbose_name='Breaking News?')),
                ('breaking_timeout', models.DateTimeField(default=django.utils.timezone.now)),
                ('seo_keyword', models.CharField(blank=True, default='', max_length=100, verbose_name='SEO Keyword')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO Description')),
                ('is_explicit', models.BooleanField(default=False, help_text='Check if this article contains advertiser-unfriendly content. Disables ads for this specific article.', verbose_name='Is Explicit?')),
                ('legacy_template', models.CharField(blank=True, default='', max_length=3000)),
                ('legacy_template_data', models.TextField(blank=True, default='')),
                ('legacy_revision_number', models.IntegerField(default=0)),
                ('layout', models.CharField(default='default', help_text='These correspond to very frequently used templates. More "bespoke", one-off templates should be added to the library of DB Templates', max_length=100, verbose_name='Article Layout')),
                ('fw_alternate_title', models.CharField(blank=True, default='', help_text='When there is a "special feature" or full-width style article, sometimes we would like to override the title as it render in the template', max_length=255, verbose_name='Alternate Title (Optional)')),
                ('fw_optional_subtitle', models.CharField(blank=True, default='', help_text='When there is a "special feature" or full-width style article, sometime we want to add a subtitle alongside the title', max_length=255, verbose_name='Subtitle (Optional)')),
                ('fw_above_cut_lede', models.TextField(blank=True, default='', help_text='Articles that use a special header/banner often contain a second lede/abstract summary ', verbose_name='Above Cut Lede (Optional)')),
                ('fw_about_this_article', models.TextField(blank=True, default='', verbose_name='About This Article (Optional)')),
                ('header_layout', models.CharField(default='right-image', help_text='Based on from Dispatch\'s obselete "Templates" feature', max_length=50)),
                ('use_default_template', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.categorysnippet')),
                ('db_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dbtemplates.template')),
                ('dispatch_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.article')),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='article.ArticlePageTag', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddIndex(
            model_name='flexpage',
            index=models.Index(fields=['current_section', 'last_modified_at'], name='article_fle_current_cb21ff_idx'),
        ),
        migrations.AddIndex(
            model_name='flexpage',
            index=models.Index(fields=['last_modified_at'], name='article_fle_last_mo_0d166e_idx'),
        ),
        migrations.AddIndex(
            model_name='flexpage',
            index=models.Index(fields=['category'], name='article_fle_categor_bf2c63_idx'),
        ),
    ]
