# Generated by Django 3.2.11 on 2022-09-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20220901_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='use_parent_colour',
            field=models.BooleanField(default=True),
        ),
    ]
