# Generated by Django 3.1.12 on 2021-07-09 10:44

from django.db import migrations, models
import django.db.models.deletion
import specialfeaturelanding.blocks
import specialfeaturelanding.validators
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('current_section', models.CharField(blank=True, default='', max_length=255)),
                ('body', wagtail.core.fields.StreamField([('dispatch_article', wagtail.core.blocks.StructBlock([('article_slug', wagtail.core.blocks.CharBlock(help_text='Type the SLUG of an article to be included here', required=True, validators=[specialfeaturelanding.validators.validate_published_article]))])), ('dispatch_article_chooser', specialfeaturelanding.blocks.DispatchArticleChooserBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
