# Generated by Django 3.2.5 on 2021-08-25 01:00

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('specialfeaturelanding', '0004_speciallandingpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciallandingpage',
            name='main_class_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='speciallandingpage',
            name='content',
            field=wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.RichTextBlock(required=False)), ('source', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('template', wagtail.core.blocks.ChoiceBlock(choices=[('guide-2020', '"Guide 2020"-Style Panel Quote')])), ('class_name', wagtail.core.blocks.CharBlock(default='panel-quote __1', max_length=255, required=True))], label='Quote Block')), ('stylecta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('richcontent', wagtail.core.blocks.RichTextBlock(required=False)), ('htmlcontent', wagtail.core.blocks.RawHTMLBlock(required=False)), ('use_richtext', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('link', wagtail.core.blocks.PageChooserBlock(required=True)), ('link_text', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('class_name', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('template', wagtail.core.blocks.ChoiceBlock(choices=[('guide-2020', '"Guide 2020"-Style CTA')]))], label='Custom Styling CTA'))], blank=True, null=True),
        ),
    ]
