# Generated by Django 3.2.5 on 2021-08-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialfeaturelanding', '0005_auto_20210824_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciallandingpage',
            name='main_class_name',
            field=models.CharField(blank=True, default='home-content-container', max_length=255),
        ),
    ]
