# Generated by Django 3.2.11 on 2022-08-23 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialfeaturelanding', '0006_alter_speciallandingpage_main_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciallandingpage',
            name='create_menu_from_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speciallandingpage',
            name='parent_page_for_menu_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='specialfeaturelanding.speciallandingpage'),
        ),
    ]
