# Generated by Django 3.2.11 on 2022-08-03 00:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_authorpage_ubyssey_role'),
        ('specialfeaturelanding', '0006_alter_speciallandingpage_main_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciallandingpage',
            name='editorial_stream',
            field=wagtail.core.fields.StreamField([('credits', wagtail.core.blocks.StreamBlock([('title', wagtail.core.blocks.CharBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock()), ('editor_credit', wagtail.core.blocks.StructBlock([('role', wagtail.core.blocks.CharBlock()), ('name', wagtail.core.blocks.CharBlock())]))])), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CreditsOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(blank=True, help_text='If null or blank, will use the name entered in "Author Name" field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authors.authorpage')),
                ('special_landing_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_credits', to='specialfeaturelanding.speciallandingpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
