# Generated by Django 3.2.11 on 2022-08-03 01:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('specialfeaturelanding', '0007_auto_20220802_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciallandingpage',
            name='editorial_stream',
            field=wagtail.core.fields.StreamField([('credits', wagtail.core.blocks.StreamBlock([('title', wagtail.core.blocks.CharBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock()), ('editor_credit', wagtail.core.blocks.StructBlock([('role', wagtail.core.blocks.CharBlock()), ('name', wagtail.core.blocks.CharBlock())]))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('note_with_header', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
