# Generated by Django 3.2.11 on 2022-08-18 00:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('specialfeaturelanding', '0008_alter_speciallandingpage_editorial_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciallandingpage',
            name='graphical_menu',
            field=wagtail.core.fields.StreamField([('menu_item', wagtail.core.blocks.StructBlock([('class_name', wagtail.core.blocks.CharBlock(default='class', max_length=255, required=True)), ('text', wagtail.core.blocks.CharBlock(default='text', max_length=255, required=True))], label='Text'))], blank=True, null=True),
        ),
    ]
