# Generated by Django 3.2.11 on 2022-09-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialfeaturelanding', '0007_auto_20220822_1756'),
        ('specialfeaturelanding', '0009_speciallandingpage_graphical_menu'),
    ]

    operations = [
    ]
