# Generated by Django 3.1.8 on 2021-06-01 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubysseyimage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.authorsnippet'),
        ),
    ]
