# Generated by Django 3.1.12 on 2021-07-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysnippet',
            name='legacy_pk',
            field=models.IntegerField(default=0),
        ),
    ]
