# Generated by Django 3.1.12 on 2021-07-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_gallerysnippet_legacy_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubysseyimage',
            name='legacy_pk',
            field=models.IntegerField(default=0),
        ),
    ]
