# Generated by Django 3.1.12 on 2021-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_ubysseyimage_legacy_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubysseyimage',
            name='legacy_authors',
            field=models.TextField(blank=True, default=''),
        ),
    ]
