# Generated by Django 3.1.12 on 2021-06-29 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_galleryorderable_gallerysnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysnippet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerysnippet',
            name='legacy_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gallerysnippet',
            name='legacy_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gallerysnippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
