# Generated by Django 3.1.12 on 2021-06-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210629_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerysnippet',
            name='legacy_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerysnippet',
            name='legacy_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
