# Generated by Django 3.1.8 on 2021-06-02 21:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.AddField(
            model_name='homepage',
            name='sections_stream',
            field=wagtail.core.fields.StreamField([('home_page_section_block', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=True))]))], blank=True, null=True),
        ),
    ]
