# Generated by Django 3.1.8 on 2021-06-02 23:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210602_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='sections_stream',
            field=wagtail.core.fields.StreamField([('home_page_section_block', wagtail.core.blocks.StructBlock([]))], blank=True, null=True),
        ),
    ]
