# Generated by Django 3.2.5 on 2021-08-27 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_adsettings'),
        ('home', '0002_auto_20210826_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_sidebar_ad_slot1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ads.adslot'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_sidebar_ad_slot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ads.adslot'),
        ),
    ]
