# Generated by Django 3.1.8 on 2021-06-03 00:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210602_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='sections_stream',
            field=wagtail.core.fields.StreamField([('home_page_section_block', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.PageChooserBlock(page_type=['section.SectionPage']))]))], blank=True, null=True),
        ),
    ]
