# Generated by Django 3.2.11 on 2022-05-26 02:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_sidebar_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='above_cut_stream',
            field=wagtail.core.fields.StreamField([('above_cut_block', wagtail.core.blocks.StructBlock([('above_cut_ad_slot', wagtailmodelchooser.blocks.ModelChooserBlock(required=False, target_model='ads.adslot'))]))], blank=True, null=True),
        ),
    ]
