# Generated by Django 3.2.11 on 2022-07-07 23:18

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_above_cut_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_leaderboard_ad_slot',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_mobile_leaderboard_ad_slot',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_sidebar_ad_slot1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_sidebar_ad_slot2',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='above_cut_stream',
            field=wagtail.core.fields.StreamField([('above_cut_block', wagtail.core.blocks.StructBlock([]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sidebar_stream',
            field=wagtail.core.fields.StreamField([('sidebar_advertisement_block', wagtail.core.blocks.StructBlock([])), ('sidebar_issuu_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255, required=True))])), ('sidebar_section_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('section', wagtail.core.blocks.PageChooserBlock(page_type=['section.SectionPage']))]))], blank=True, null=True),
        ),
    ]
