# Generated by Django 3.1.12 on 2021-06-24 20:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenuOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('external_link', models.URLField(blank=True, default='')),
                ('link_text', models.CharField(blank=True, default='', max_length=25, verbose_name='Link Text (Optional)')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SitewideMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site-Wide Menus',
                'verbose_name_plural': "Instances of 'Site-Wide Menus'",
            },
        ),
        migrations.CreateModel(
            name='SecondFooterNavigationItem',
            fields=[
                ('navigationmenuorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='navigation.navigationmenuorderable')),
                ('navigation_menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_footer_menu', to='navigation.sitewidemenus')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('navigation.navigationmenuorderable',),
        ),
        migrations.CreateModel(
            name='RightHeaderNavigationItem',
            fields=[
                ('navigationmenuorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='navigation.navigationmenuorderable')),
                ('navigation_menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_header_menu', to='navigation.sitewidemenus')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('navigation.navigationmenuorderable',),
        ),
        migrations.CreateModel(
            name='MobileLinksNavigationItem',
            fields=[
                ('navigationmenuorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='navigation.navigationmenuorderable')),
                ('navigation_menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_links_menu', to='navigation.sitewidemenus')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('navigation.navigationmenuorderable',),
        ),
        migrations.CreateModel(
            name='MainHeaderNavigationItem',
            fields=[
                ('navigationmenuorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='navigation.navigationmenuorderable')),
                ('navigation_menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_header_menu', to='navigation.sitewidemenus')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('navigation.navigationmenuorderable',),
        ),
        migrations.CreateModel(
            name='MainFooterNavigationItem',
            fields=[
                ('navigationmenuorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='navigation.navigationmenuorderable')),
                ('navigation_menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_footer_menu', to='navigation.sitewidemenus')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('navigation.navigationmenuorderable',),
        ),
        migrations.CreateModel(
            name='LeftHeaderNavigationItem',
            fields=[
                ('navigationmenuorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='navigation.navigationmenuorderable')),
                ('navigation_menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_header_menu', to='navigation.sitewidemenus')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('navigation.navigationmenuorderable',),
        ),
    ]
