# Generated by Django 3.1.8 on 2021-06-07 23:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenuitem',
            name='external_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='navigationmenuitem',
            name='internal_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='navigationmenuitem',
            name='link_text',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='navigationmenuitem',
            name='navigation_menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_menu_item', to='navigation.navigationmenu'),
        ),
        migrations.CreateModel(
            name='SitewideMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_header_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='navigation.navigationmenu')),
                ('main_footer_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='navigation.navigationmenu')),
                ('main_header_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='navigation.navigationmenu')),
                ('right_header_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='navigation.navigationmenu')),
                ('second_footer_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='navigation.navigationmenu')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Sitewide Menus',
            },
        ),
    ]
