# Generated by Django 3.1.12 on 2021-06-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenuorderable',
            name='link_text',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Link Text (Optional)'),
        ),
    ]
