# Generated by Django 3.1.8 on 2021-06-07 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20210607_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitewidemenus',
            options={'verbose_name': 'Site-Wide Menus', 'verbose_name_plural': "Instances of 'Site-Wide Menus'"},
        ),
        migrations.AlterField(
            model_name='sitewidemenus',
            name='left_header_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigation.navigationmenu'),
        ),
    ]
