# Generated by Django 3.1.8 on 2021-06-08 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_auto_20210607_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidemenus',
            name='mobile_links_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='navigation.navigationmenu'),
        ),
        migrations.AlterField(
            model_name='navigationmenuitem',
            name='link_text',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
