# Generated by Django 3.1.12 on 2021-06-14 21:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0063_auto_20210614_1318'),
        ('navigation', '0005_auto_20210607_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftHeaderNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_text', models.CharField(blank=True, default='', max_length=25)),
                ('external_link', models.URLField(blank=True, default='')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainFooterNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_text', models.CharField(blank=True, default='', max_length=25)),
                ('external_link', models.URLField(blank=True, default='')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainHeaderNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_text', models.CharField(blank=True, default='', max_length=25)),
                ('external_link', models.URLField(blank=True, default='')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileLinksNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_text', models.CharField(blank=True, default='', max_length=25)),
                ('external_link', models.URLField(blank=True, default='')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RightHeaderNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_text', models.CharField(blank=True, default='', max_length=25)),
                ('external_link', models.URLField(blank=True, default='')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondFooterNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_text', models.CharField(blank=True, default='', max_length=25)),
                ('external_link', models.URLField(blank=True, default='')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='navigationmenuitem',
            name='internal_link',
        ),
        migrations.RemoveField(
            model_name='navigationmenuitem',
            name='navigation_menu',
        ),
        migrations.RemoveField(
            model_name='sitewidemenus',
            name='left_header_menu',
        ),
        migrations.RemoveField(
            model_name='sitewidemenus',
            name='main_footer_menu',
        ),
        migrations.RemoveField(
            model_name='sitewidemenus',
            name='main_header_menu',
        ),
        migrations.RemoveField(
            model_name='sitewidemenus',
            name='mobile_links_menu',
        ),
        migrations.RemoveField(
            model_name='sitewidemenus',
            name='right_header_menu',
        ),
        migrations.RemoveField(
            model_name='sitewidemenus',
            name='second_footer_menu',
        ),
        migrations.DeleteModel(
            name='NavigationMenu',
        ),
        migrations.DeleteModel(
            name='NavigationMenuItem',
        ),
        migrations.AddField(
            model_name='secondfooternavigationitem',
            name='navigation_menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_footer_menu', to='navigation.sitewidemenus'),
        ),
        migrations.AddField(
            model_name='rightheadernavigationitem',
            name='navigation_menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_header_menu', to='navigation.sitewidemenus'),
        ),
        migrations.AddField(
            model_name='mobilelinksnavigationitem',
            name='navigation_menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_links_menu', to='navigation.sitewidemenus'),
        ),
        migrations.AddField(
            model_name='mainheadernavigationitem',
            name='navigation_menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_header_menu', to='navigation.sitewidemenus'),
        ),
        migrations.AddField(
            model_name='mainfooternavigationitem',
            name='navigation_menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_footer_menu', to='navigation.sitewidemenus'),
        ),
        migrations.AddField(
            model_name='leftheadernavigationitem',
            name='navigation_menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_header_menu', to='navigation.sitewidemenus'),
        ),
    ]
