# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('host', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'images/events/')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('location', models.CharField(max_length=500)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[(b'sports', b'Sports'), (b'music', b'Music'), (b'academic', b'Academic'), (b'party', b'Party'), (b'business', b'Business'), (b'ceremony', b'Ceremony'), (b'workshop', b'Workshop'), (b'clubs', b'Clubs'), (b'other', b'Other')], max_length=20)),
                ('event_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('event_url', models.TextField(blank=True, null=True)),
                ('ticket_url', models.TextField(blank=True, null=True)),
                ('is_submission', models.BooleanField(default=False)),
                ('is_submission_email', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_published_email', models.BooleanField(default=False)),
                ('submitter_email', models.EmailField(max_length=254, null=True)),
                ('submitter_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True)),
            ],
        ),
    ]
