# Generated by Django 3.1.8 on 2021-05-21 00:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsTournamentSnippet',
            fields=[
                ('tournament_name', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsTeamOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('team_name', models.TextField(blank=True, default='')),
                ('team_color', models.CharField(default='#FF0000', max_length=7)),
                ('team_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsPlayerProfileOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_text', models.CharField(blank=True, max_length=1500)),
                ('player_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('players_team', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_to_watch', to='sporttourney.sportsteamorderable')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
