# Generated by Django 3.1.8 on 2021-05-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sporttourney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsplayerprofile',
            name='players_team',
        ),
    ]
