# Generated by Django 3.1.8 on 2021-05-21 22:17

from django.db import migrations, models
import ubyssey.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sporttourney', '0002_remove_sportsplayerprofile_players_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsteamorderable',
            name='team_color',
            field=models.CharField(default='#FF0000', max_length=7, validators=[ubyssey.validators.validate_colour_hex]),
        ),
    ]
