# Generated by Django 3.0.7 on 2021-03-07 06:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazineissue',
            name='year',
        ),
        migrations.AddField(
            model_name='magazineissue',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m'),
        ),
        migrations.AddField(
            model_name='magazineissue',
            name='description',
            field=models.CharField(default='The Ubyssey Magazine', max_length=100),
        ),
        migrations.AddField(
            model_name='magazineissue',
            name='pubdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='magazineissue',
            name='social_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m'),
        ),
        migrations.AddField(
            model_name='magazineissue',
            name='title',
            field=models.CharField(default='The Ubyssey Magazine', max_length=100),
        ),
        migrations.CreateModel(
            name='MagazineSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='Magazine Section', max_length=100)),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.MagazineIssue')),
            ],
        ),
    ]
